service: finesse
image: scudco/finesse

servers:
  web:
    - 64.225.28.77
  job:
    hosts:
      - 64.225.28.77
    cmd: bin/jobs
  sse:
    hosts:
      - 64.225.28.77
    cmd: bin/sse-server
    proxy:
      ssl: true
      host: chat-sse.scud.co
      app_port: 4000
      healthcheck:
        path: /up

proxy:
  ssl: true
  host: chat.scud.co

registry:
  server: registry.digitalocean.com
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: false
    CABLE_DB_PATH: storage/production_cable.sqlite3
    SSE_HOST: https://chat-sse.scud.co

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "finesse_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64
